PROJECT_NAME = "Password Generator"
WINDOW_WIDTH = 350
WINDOW_HEIGHT = 300

FONT_FAMILY = "Arial"
FONT_SIZE = 10

PADDING_HEIGHT = 5
PADDING_WIDTH = 5

FORMULARY_FRAME_PADDING_WIDTH = PADDING_WIDTH * 14

HEADING_LABEL_FONT_SIZE = FONT_SIZE + 6
HEADING_LABEL_PADDING_HEIGHT = PADDING_HEIGHT * 2

INITIAL_MESSAGE_PASSWORD_ENTRY = "Your password will be written here"
PASSWORD_ENTRY_WIDTH = len(INITIAL_MESSAGE_PASSWORD_ENTRY)

LABELFRAME_WITH_PASSWORD_OPTIONS_LABEL = "Options"

CHARACTERS_NUMBER_LABEL_TEXT = "Number of characters"

PASSWORD_GENERATION_BUTTON_TEXT = "Generate Password"
COPY_PASSWORD_BUTTON_TEXT = "Copy Password"