PROJECT_NAME = "Password Generator"
WINDOW_WIDTH = 350
WINDOW_HEIGHT = 300

FONT_FAMILY = "Arial"
FONT_SIZE = 10
PADDING_HEIGHT = 5

PROJECT_TITLE_FONT_SIZE = FONT_SIZE + 6
PROJECT_TITLE_PADDING_HEIGHT = PADDING_HEIGHT * 2

BUTTON_TEXT = "Generate Password"

INITIAL_MESSAGE_PASSWORD_ENTRY = "Your password will be written here"
PASSWORD_ENTRY_WIDTH = len(INITIAL_MESSAGE_PASSWORD_ENTRY)